---
# playbook n°5 : Modification de port 

- name: modifier le port 80 en 8080
  hosts: all
  gather_facts: false
  remote_user: vagrant
  become: yes

  tasks: 
    - name: changement de port 
      lineinfile:
        path: '{{path_conf_port}}'
        regexp: ^Listen 80$ 
        line: Listen 8080
      notify: restart_services

  handlers:
    - name: demarrer le service httpd
      service: 
        name: '{{service}}'
        state: restarted
      listen: restart_services

