---
# playbook n°5 : installation de httpd sur les centos

- name: installation de httpd
  hosts: all
  gather_facts: false
  remote_user: vagrant
  become: yes

  tasks: 
    - name: installer les serveurs web
      package: 
        name: '{{paquet}}'
        state: present
  
    - name: demarrer les services
      service: 
        name: '{{service}}'
        state: started
        enabled: true
   
    - name: copier le fichier html dans les nodes
      copy:
        src: index.html
        dest: '{{repertoire}}' 

