---
# playbook n°3 : Modification de port 

- name: modifier le port 80 en 8080
  hosts: centos
  gather_facts: false
  remote_user: vagrant
  become: yes

  tasks: 
    - name: changement de port 
      lineinfile:
        path: '{{httpd_conf}}'
        regexp: ^Listen 80$ 
        line: Listen 8080
      notify: restart_httpd

  handlers:
    - name: demarrer le service httpd
      service: 
        name: '{{service_name}}'
        state: restarted
      listen: restart_httpd

