---
 - name : Module assert 
   hosts: all

   tasks:

   - name: Vérification de la distribution CentOs/RedHat et de m'architecture x86_64
     assert:
       that:
         - ansible_distribution in ['CentOS','RedHat']
         - ansible_architecture == 'x86_64'
       fail_msg: Distribution/architecture non supportée
       success_msg: Tout est OK

   - name: Tache  de Vérification de la réussite du module assert
     debug: 
       msg: "Glop glop !"
